[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Donate"
  pageRef = "/#donate"
  weight = 20
# button = true

[[main]]
  name = "Terms of Service"
  pageRef = "/tos"
  weight = 30

[[social]]
  name = "Matrix"
  pre = "fab matrix"
  url = "https://matrix.to/#/#diasp.in:poddery.com/"
  weight = 10

[[social]]
  name = "XMPP"
  pre = "fab fa-xmpp"
  url = "https://xmpp.link/#diasp.in@conference.diasp.in?join"
  weight = 20

[[social]]
  name = ""
  pre = "fab fa-gitlab"
  url = "https://gitlab.com/piratemovin/diasp.in"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation
